[project]
name = "dependency-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hrushikesh", email = "hrushikesh.vpawar@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cyclopts>=3.16.1",
    "graphviz>=0.20.3",
    "loguru>=0.7.3",
    "networkx>=3.4.2",
    "plsql-analyzer",
    "pyvis>=0.3.2",
    "tqdm>=4.67.1",
]

[project.scripts]
dependency-analyzer = "dependency_analyzer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
plsql-analyzer = { workspace = true }

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "numpy>=2.2.5",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "pytest-xdist[psutil]>=3.6.1",
    "scipy>=1.15.3",
    "snakeviz>=2.2.2",
]
