[project]
name = "plsql-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hrushikesh", email = "hrushikesh.pawar@evernorth.com" }
]
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pyparsing[diagrams]>=3.2.3",
    "regex>=2024.11.6",
    "tqdm>=4.67.1",
]

[project.scripts]
plsql-analyzer = "plsql_analyzer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "pytest-xdist[psutil]>=3.6.1",
    "snakeviz>=2.2.2",
]
